package inputs

import "code.internetisalie.net/gomplate/pkg/generate"

//go:generate go run code.internetisalie.net/gomplate/cmd/generate

var Constants = generate.Gomplate{
	OutputFile: "/gen/constants.go",
	Data: []struct {
		Name string `json:"name"`
		Key  string `json:"key"`
	}{
		{
			Name: "One",
			Key:  "One",
		},
	},
	// language=GoTemplate
	Template: `
{{- $data := ds "data" -}}
// Code generated by gomplate. DO NOT EDIT.

package gen

const (
{{- range $entry := $data }}
	Flag{{$entry.name}} = "{{$entry.key}}"
{{- end }}
)

var Flags = []string{
{{- range $entry := $data }}
	Flag{{$entry.name}},
{{- end}}
}
`,
}
